-- sql/01_setup.sql
-- Create a writable workspace and copy the TPC-DS sample tables.

CREATE DATABASE IF NOT EXISTS WORK_DB;
CREATE SCHEMA  IF NOT EXISTS WORK_DB.TPCDS;
USE SCHEMA WORK_DB.TPCDS;

CREATE OR REPLACE TABLE STORE_SALES AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES;

CREATE OR REPLACE TABLE DATE_DIM AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.DATE_DIM;

CREATE OR REPLACE TABLE CUSTOMER AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER;
