-- sql/05_reports.sql
-- Baseline report against the original tables (your style).

USE SCHEMA WORK_DB.TPCDS;

SELECT C_BIRTH_COUNTRY,
  SUM(CASE WHEN D_DAY_NAME='Monday'    THEN COALESCE(SS_NET_PROFIT,0) ELSE 0 END) AS Monday,
  SUM(CASE WHEN D_DAY_NAME='Tuesday'   THEN COALESCE(SS_NET_PROFIT,0) ELSE 0 END) AS Tuesday,
  SUM(CASE WHEN D_DAY_NAME='Wednesday' THEN COALESCE(SS_NET_PROFIT,0) ELSE 0 END) AS Wednesday,
  SUM(CASE WHEN D_DAY_NAME='Thursday'  THEN COALESCE(SS_NET_PROFIT,0) ELSE 0 END) AS Thursday,
  SUM(CASE WHEN D_DAY_NAME='Friday'    THEN COALESCE(SS_NET_PROFIT,0) ELSE 0 END) AS Friday,
  SUM(CASE WHEN D_DAY_NAME='Saturday'  THEN COALESCE(SS_NET_PROFIT,0) ELSE 0 END) AS Saturday,
  SUM(CASE WHEN D_DAY_NAME='Sunday'    THEN COALESCE(SS_NET_PROFIT,0) ELSE 0 END) AS Sunday
FROM STORE_SALES s
LEFT JOIN DATE_DIM d
  ON s.ss_sold_date_sk = d.d_date_sk
LEFT JOIN CUSTOMER c 
  ON s.ss_customer_sk = c.c_customer_sk
WHERE d.d_year = 2000
  AND c.c_birth_country IS NOT NULL
GROUP BY C_BIRTH_COUNTRY
ORDER BY C_BIRTH_COUNTRY;
